### ISSUE TITLE
Android版本在Win7下无法安装运行

### ISSUE THREAD

**Issue by gongzelong0718** [Bob1993/React-Native-Gank#17]
可以跑自己的小demo。
不过无法安装这个开源项目。
以下是在Terminal中的命令。

Welcome to Git (version 1.9.5-preview20150319)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

GongZelong@HECOM-PC /D/AndroidSelfTrainingProject/React-Native-Gank (master)
$ npm install
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\fbjs requires core-js@'^1.0.0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\core-js,
npm WARN unmet dependency which is version 2.4.0
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-register\node_modules\source-map-support
requires source-map@'0.1.32' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\source-map,
npm WARN unmet dependency which is version 0.4.4
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-react-transform requires lodash@'^4.6.1' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-es2015-classes\node_modules\babel-template requires lodash@'^4.2.
0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-es2015-classes\node_modules\babel-traverse requires lodash@'^4.2.
0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-es2015-classes\node_modules\babel-helper-define-map requires loda
sh@'^4.2.0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-es2015-function-name\node_modules\babel-helper-function-name\node
_modules\babel-traverse requires lodash@'^4.2.0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-es2015-function-name\node_modules\babel-helper-function-name\node
_modules\babel-template requires lodash@'^4.2.0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-es2015-parameters\node_modules\babel-traverse requires lodash@'^4
.2.0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-es2015-parameters\node_modules\babel-template requires lodash@'^4
.2.0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-preset-react-native\node_modules\babel-pl
ugin-transform-regenerator\node_modules\babel-traverse requires lodash@'^4.2.0'
but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\fbjs-scripts\node_modules\babel requires babel-
core@'^5.6.21' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\babel-core,
npm WARN unmet dependency which is version 6.10.4
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\fbjs-scripts\node_modules\babel requires source
-map@'^0.5.0' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\source-map,
npm WARN unmet dependency which is version 0.4.4
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\uglify-js\node_modules\yargs\node_modules\cliui
 requires wordwrap@'0.0.2' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\react-native\node_modules\wordwrap,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\escope\node_modules\es6-map\node_modules\es5-ext requ
ires es6-symbol@'~3.0.2' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\escope\node_modules\es6-map\node_modules\es6-symbol,
npm WARN unmet dependency which is version 3.1.0
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\escope\node_modules\es6-weak-map\node_modules\es5-ext
 requires es6-symbol@'~3.0.2' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\escope\node_modules\es6-weak-map\node_modules\es6-sym
bol,
npm WARN unmet dependency which is version 3.1.0
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\handlebars\node_modules\uglify-js requires async@'~0.
2.6' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\handlebars\node_modules\async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\handlebars\node_modules\uglify-js requires source-map
@'~0.5.1' but will load
npm WARN unmet dependency d:\AndroidSelfTrainingProject\React-Native-Gank\node_m
odules\eslint\node_modules\handlebars\node_modules\source-map,
npm WARN unmet dependency which is version 0.4.4

GongZelong@HECOM-PC /D/AndroidSelfTrainingProject/React-Native-Gank (master)
$ react-native run-android
module.js:327
    throw err;
    ^

Error: Cannot find module 'core-js/fn/array/values'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (d:\AndroidSelfTrainingProject\React-Native-Gank\node_
modules\react-native\packager\babelRegisterOnly.js:11:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by poberwong** [comment]
你应该是npm install 的时候，依赖没有安装好.... 我也没有用一些私有库，都是public的。刚刚重新clone跑了一遍，可以跑通呀～

**Comment by gongzelong0718** [comment]
我是在Win7下，你也是在相同环境，使用npm install?

**Comment by poberwong** [comment]
OSX：
- npm: v3.8.6
- node: v6.1.0
- react-native-cli: v0.2.0
- react-native: v0.25.1

**Comment by gongzelong0718** [comment]
我的环境如下，差别还蛮大的，哎，不好定位问题了……

Win7：
- npm: v2.15.5
- node: v4.4.6
- react-native: v1.0.0
- react-native-cli: v0.25.1

D:\AndroidSelfTrainingProject\React-Native-Gank>react-native --version
react-native-cli: 1.0.0
react-native: 0.25.1

D:\AndroidSelfTrainingProject\React-Native-Gank>npm -v
2.15.5

D:\AndroidSelfTrainingProject\React-Native-Gank>node -v
v4.4.6

**Comment by poberwong** [comment]
远离Windows，珍爱生命
